### ISSUE TITLE
Config file for ease of use

### ISSUE THREAD

**Issue by OneHappyForever** [shadowsocks/go-shadowsocks2#62] opened 2017-08-09 07:27 UTC
Hello,

It seems there is no option to create a configuration file (e.g. Config.json) like there is for shadowsocks-libev. This would make it much easier to run instead of always typing the details each time you run shadowsocks2.

Best regards,

**Comment by riobard** [comment] 2017-08-09 09:54
Duplicate of #15

**Closed by riobard** 2017-08-09 09:54 UTC
Labels: duplicate
